Update basic_types.h
Should ressolve error, forgot to change the corresponding member variable, the constructor parameter is initializing.

 Const:   --- stderr: moveit_core
  In file included from /home/runner/work/moveit2/moveit2/.work/target_ws/src/moveit2/moveit_core/collision_detection_bullet/src/bullet_integration/bullet_utils.cpp:35:
  In file included from /home/runner/work/moveit2/moveit2/.work/target_ws/src/moveit2/moveit_core/collision_detection_bullet/include/moveit/collision_detection_bullet/bullet_integration/bullet_utils.h:41:
  /home/runner/work/moveit2/moveit2/.work/target_ws/src/moveit2/moveit_core/collision_detection_bullet/include/moveit/collision_detection_bullet/bullet_integration/basic_types.h:64:40: error: binding reference member 'contact_distance' to stack allocated parameter 'contact_distance' [-Werror,-Wdangling-field]
      : active(active), contact_distance(contact_distance), res(res), req(req), done(false), pair_done(false)
                                         ^~~~~~~~~~~~~~~~
  /home/runner/work/moveit2/moveit2/.work/target_ws/src/moveit2/moveit_core/collision_detection_bullet/include/moveit/collision_detection_bullet/bullet_integration/basic_types.h:71:17: note: reference member declared here
    const double& contact_distance;
                  ^
  1 error generated.
  gmake[2]: *** [collision_detection_bullet/CMakeFiles/moveit_collision_detection_bullet.dir/build.make:76: collision_detection_bullet/CMakeFiles/moveit_collision_detection_bullet.dir/src/bullet_integration/bullet_utils.cpp.o] Error 1
  gmake[1]: *** [CMakeFiles/Makefile2:674: collision_detection_bullet/CMakeFiles/moveit_collision_detection_bullet.dir/all] Error 2
  gmake[1]: *** Waiting for unfinished jobs....
  gmake: *** [Makefile:146: all] Error 2
  ---